
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package cup.example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int AND = 18;
  public static final int ELSE = 5;
  public static final int OR = 19;
  public static final int THEN = 4;
  public static final int SEMI = 21;
  public static final int WHILE = 3;
  public static final int NOT = 20;
  public static final int PLUMADIR = 14;
  public static final int N = 24;
  public static final int num = 27;
  public static final int IF = 2;
  public static final int TABCOL = 12;
  public static final int BRACKETR = 23;
  public static final int DO = 10;
  public static final int AVAZ = 11;
  public static final int COLORP = 8;
  public static final int BORDE = 13;
  public static final int EOF = 0;
  public static final int BRACKETL = 22;
  public static final int PLUMAUP = 16;
  public static final int PLUMADOWN = 17;
  public static final int error = 1;
  public static final int BAJARP = 6;
  public static final int DIRP = 9;
  public static final int d = 26;
  public static final int c = 25;
  public static final int PLUMACOL = 15;
  public static final int SUBIRP = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "WHILE",
  "THEN",
  "ELSE",
  "BAJARP",
  "SUBIRP",
  "COLORP",
  "DIRP",
  "DO",
  "AVAZ",
  "TABCOL",
  "BORDE",
  "PLUMADIR",
  "PLUMACOL",
  "PLUMAUP",
  "PLUMADOWN",
  "AND",
  "OR",
  "NOT",
  "SEMI",
  "BRACKETL",
  "BRACKETR",
  "N",
  "c",
  "d",
  "num"
  };
}

